apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-autoscaler-settings
  namespace: kube-system
data:
  cluster-name: dev-gke
  node-group-auto-discovery: namePrefix:gke-dev-gke-
  max-nodes-total: "40"
  scale-down-delay-after-add: 5m
  scale-down-unneeded-time: 3m
  scan-interval: 10s
