apiVersion: v1
kind: Service
metadata:
  name: service-a
  labels:
    app: service-a
spec:
  type: ClusterIP
  selector:
    app: service-a
  ports:
    - name: http
      port: 80
      targetPort: 80
