apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-autoscaler
  namespace: kube-system
  annotations:
    iam.gke.io/gcp-service-account: cluster-autoscaler-staging@REPLACE_WITH_PROJECT_ID.iam.gserviceaccount.com
