apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-template
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/version: "1.0.0"
    spec:
      containers:
        - name: api
          image: ghcr.io/your-org/service-template:prod
          envFrom:
            - configMapRef:
                name: service-template-config
          env:
            - name: FEATURE_FLAG_PREVIEW
              value: "false"
            - name: ENABLE_TELEMETRY
              value: "true"
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 1
              memory: 1024Mi
