apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - pdb.yaml
commonLabels:
  app.kubernetes.io/name: service-template
  app.kubernetes.io/part-of: service-template
  app.kubernetes.io/component: api
  app.kubernetes.io/managed-by: gitops
