# Checkov configuration (Terraform)

framework:
  - terraform

skip-check:
  - id: CKV_AZURE_115
    comment: "Private cluster disabled intentionally for local/dev usage"
  - id: CKV_AZURE_226
    comment: "Ephemeral OS disks not supported on all target SKUs"
  - id: CKV_AZURE_227
    comment: "Disk encryption handled via platform-managed keys outside Terraform"
  - id: CKV_AZURE_168
    comment: "Pod density tuned per workload; validated in separate policy"

# Quiet output suitable for CI; adjust as needed
quiet: true
compact: true

# Optional: write SARIF/JSON output reports
# output: sarif
# output-file-path: reports/checkov.sarif