apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-template
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/version: "0.2.0-rc"
    spec:
      containers:
        - name: api
          image: ghcr.io/your-org/service-template:staging
          envFrom:
            - configMapRef:
                name: service-template-config
          env:
            - name: FEATURE_FLAG_PREVIEW
              value: "true"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
